//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public string Formula { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> SoldPricePerUnit { get; set; }
        public Nullable<decimal> RetailPricePerUnit { get; set; }
        public Nullable<int> TabletQuantityPerPacket { get; set; }
        public Nullable<decimal> TotalSoldPrice { get; set; }
        public Nullable<decimal> TotalPurchasePrice { get; set; }
        public Nullable<int> TotalTabletStock { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
